-- Simple ELISA PDF table
CREATE TABLE IF NOT EXISTS `tbl_elisa_pdf` (
  `pdfId` INT NOT NULL AUTO_INCREMENT,
  `PIId` INT NOT NULL,
  `pdfName` VARCHAR(255) NOT NULL,
  `fileName` VARCHAR(255) NOT NULL UNIQUE,
  `filePath` VARCHAR(500) NOT NULL,
  `fileSize` INT NOT NULL,
  `uploadDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pdfId`),
  INDEX `idx_PIId` (`PIId` ASC),
  CONSTRAINT `fk_elisa_pdf_PI`
    FOREIGN KEY (`PIId`)
    REFERENCES `tbl_pi` (`PIId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
